### PR TITLE
Bump minimum supported Rust version to 1.41.0

### PR DESCRIPTION
**Pull request by chrisduerr**

### CODE REVIEW

**Review by chrisduerr — COMMENTED** [review]
This bumps the version to 1.41.0 to make use of the new Cargo.lock format. That makes things a little easier to work with and should allow me to rebase https://github.com/alacritty/vtebench/pull/21 without CI failing a bunch.

**Review by kchibisov — APPROVED** [review]
We may want to do something like that for alacritty, since we're using rust 1.43 there.

**Comment by chrisduerr** [comment]
You mean update the lockfile to the new version?

**Comment by kchibisov** [comment]
>You mean update the lockfile to the new version?

Yeah.

**Comment by chrisduerr** [comment]
Makes sense. I don't think there's any rush but it is probably good to do it sooner, rather than later. Since we require 1.43+ anyways, there's no reason not to.

**Pull request merged**
