### PR TITLE
Increase gnuplot canvas size

### PR DESCRIPTION
**Pull request by planet36**
Increase gnuplot canvas size from 1000x750 to 1920x1080.

### CODE REVIEW

**Comment by chrisduerr** [comment]
Why?

**Comment by planet36** [comment]
I run the benchmark in these terminals:
- alacritty
- kitty
- lxterminal
- mate-terminal
- sakura
- st
- terminator
- tilix
- xfce4-terminal
- xterm
- zutty

When the results are plotted on a small image, it looks cramped.
If the image is larger, it looks clearer.

**Comment by kchibisov** [comment]
Could you at least show us before and after with the terminals you've used? So we can at least see that without going though that?

**Comment by chrisduerr** [comment]
This seems rather pointless, the entire argument is basically "when benchmarking 11 terminals, the default doesn't have enough space".

So if you increase the size and benchmark 20 terminals, there's still not going to be enough space.

And benchmarking different terminals against each other using only vtebench is a terrible idea anyway. So you gain nothing by being able to compare 11 terminals in the same image when the relationship between those different terminals is completely meaningless.

The main focus of vtebench is to be able to selectively compare two equal terminals, ideally two versions of the same emulator, with each other. Sometimes it might happen that you want to compare a couple more versions, but realistically I've never seen that exceed ~5. So I don't think for the **defaults** we need to consider the usecase of combining 11 results.

**Comment by planet36** [comment]
> The main focus of vtebench is to be able to selectively compare two equal terminals, ideally two versions of the same emulator, with each other. Sometimes it might happen that you want to compare a couple more versions, but realistically I've never seen that exceed ~5. So I don't think for the **defaults** we need to consider the usecase of combining 11 results.

Understood now.
Can you recommend any benchmarking tools that are better for what I was comparing?

**Comment by chrisduerr** [comment]
> Can you recommend any benchmarking tools that are better for what I was comparing?

There isn't. Benchmarking terminals requires at least *some* understanding of how the terminal to be benchmarked works and which metrics you're actually trying to capture. Just blindly running any benchmark won't really get you anywhere.

That's why there's a disclaimer in the readme:

https://github.com/alacritty/vtebench#disclaimer

**Pull request closed without merging**
